### ISSUE TITLE
Path must be a string. Received null

### ISSUE THREAD

**Issue by seanc** [generate/generate#30]
Generate Version: v0.11.2
Node Version: v6.4.0

After running `gen project license`, I received this error:

``` shell
[[90m04:03:13[39m] starting generate
[[90m04:03:13[39m] [32m✔[39m [32mrunning tasks:[39m [ 'project', 'license' ]
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1148:7)
    at Function.resolve (/home/sean/.npm-global/lib/node_modules/generate-project/node_modules/parse-git-config/index.js:107:15)
    at Function.parseSync [as sync] (/home/sean/.npm-global/lib/node_modules/generate-project/node_modules/parse-git-config/index.js:78:24)
    at Schema.module.exports (/home/sean/.npm-global/lib/node_modules/generate-project/node_modules/expand-pkg/lib/expanders/git.js:13:36)
    at Schema.normalizeField (/home/sean/.npm-global/lib/node_modules/generate-project/node_modules/map-schema/index.js:557:16)
    at Schema.update (/home/sean/.npm-global/lib/node_modules/generate-project/node_modules/map-schema/index.js:246:8)
    at Schema.module.exports (/home/sean/.npm-global/lib/node_modules/generate-project/node_modules/expand-pkg/lib/expanders/owner.js:14:10)
    at Schema.normalizeField (/home/sean/.npm-global/lib/node_modules/generate-project/node_modules/map-schema/index.js:557:16)
    at Schema.normalize (/home/sean/.npm-global/lib/node_modules/generate-project/node_modules/map-schema/index.js:497:27)
```

Asciinema: http://asciinema.org/a/8291tcxfnt46fok40dx5mus4z

**Comment by jonschlinkert** [comment]
Mind if I ask what OS/File system are you using? Also, are you using a custom npm prefix?  thanks for reporting

**Comment by tunnckoCore** [comment]
> Also, are you using a custom npm prefix?

Yea. It can be seen in the stack `/home/sean/.npm-global/lib/node_modules`.

Maybe some underling libs are not updated to get latest changes from `npm-prefix` (and related) update?

**Comment by jonschlinkert** [comment]
> It can be seen in the stack

doh! lol I see that now thx, I was waking up at the time.

**Comment by seanc** [comment]
OS: Linux Mint 18 Sarah 64-bit
File system: ext4

**Comment by seanc** [comment]
i've been experimenting, and it looks like the issue is due to git, i haven't entirely figured out why this issue is caused by git but i believe it is because one of the packages (perhaps expand-pkg) is trying to parse something from git and it's not handling null values correctly. hopefully that gives at least a bit of insight

**Comment by doowb** [comment]
@seanc will you uninstall `generate`, clear your npm cache, reinstall `generate`, then try the generators?

You may have to reinstall specific generators too.

I updated `expand-pkg` to use the latest `parse-git-config` which already had the fix but just needed to be bumped in dependent modules.

**Comment by seanc** [comment]
looks like it works now.

**Comment by jonschlinkert** [comment]
Sounds like this was resolved, I'm going to close but please feel free to reopen or create a new issue if you're still having problems.

**Comment by seanc** [comment]
looks like this still occurs in version 0.14.0. found that if there is no initialized git dir, it spits that error out, after running `git init` everything ran normally.

**Comment by jonschlinkert** [comment]
> after running git init everything ran normally.

definitely sounds like a bug. I'll open a new issue
