### ISSUE TITLE
Error: no writecb in Transform class     

### ISSUE THREAD

**Issue by seanc** [generate/generate#44]
![image](http://asciinema2gif.host/gif/7ayffo11pq3prjnhmc9ug0kl5)

```
Error: no writecb in Transform class                                                       
    at afterTransform (/home/sean/.yarn-config/global/node_modules/through2/node_modules/re
adable-stream/lib/_stream_transform.js:74:40)                                              
    at TransformState.afterTransform (/home/sean/.yarn-config/global/node_modules/through2/
node_modules/readable-stream/lib/_stream_transform.js:58:12)                               
    at handleError (/home/sean/.yarn-config/global/node_modules/assemble-render-file/index.
js:109:3)                                                                                  
    at /home/sean/.yarn-config/global/node_modules/assemble-render-file/index.js:84:15     
    at /home/sean/.yarn-config/global/node_modules/base-routes/index.js:161:11             
    at /home/sean/.yarn-config/global/node_modules/base-routes/index.js:90:25              
    at /home/sean/.yarn-config/global/node_modules/en-route/lib/index.js:576:15            
    at next (/home/sean/.yarn-config/global/node_modules/en-route/lib/index.js:161:14)     
    at next (/home/sean/.yarn-config/global/node_modules/en-route/lib/route.js:65:14)      
    at Layer.handleFile (/home/sean/.yarn-config/global/node_modules/en-route/lib/layer.js:
78:5)   
```

It happens after entering all of my information as seen in the asciinema above.

**Comment by jonschlinkert** [comment]
Thanks for the issue, I'm debugging now

**Comment by jamen** [comment]
I'm getting this error randomly too.  Although, it was working just today and I never updated any packages. :thinking:

**Comment by jamen** [comment]
So, the issue seems to be related to using quotes inside of the description field.  Like, in the example posted, you can see `"macro"`.

**Comment by jonschlinkert** [comment]
ohh, good catch! that makes sense, we should probably add something to do escaping on the values.

**Comment by jamen** [comment]
@jonschlinkert maybe escaping backslashes? e.g. `\` to `\\`?
