### ISSUE TITLE
Can't use global generator, which has been installed using `pnpm`

### ISSUE THREAD

**Issue by Andrew15-5** [generate/generate#53]
I saw some similar issues, but I think this is different.

I was using `npm` for a long while (and the package did work) and relatively recently I've watched about how cool `pnpm` is and switched to it. It can sometime give errors when `npm` won't, but these are rare cases AFAIK. And this is probably one of those rare cases.

To test the issue, install `pnpm` and run `pnpm add -g generate generate-license`. Then `gen license`:

```text
[19:42:33] starting generate
[19:42:33] ✔ running tasks: [ 'license' ]
Error: Cannot find generator: "license" in "/tmp"
    at Generate.<anonymous> (/home/user/.local/share/pnpm/global/5/.pnpm/base-generators@0.4.6/node_modules/base-generators/index.js:499:18)
    at iterate (/home/user/.local/share/pnpm/global/5/.pnpm/async-each-series@1.1.0/node_modules/async-each-series/index.js:8:5)
    at module.exports (/home/user/.local/share/pnpm/global/5/.pnpm/async-each-series@1.1.0/node_modules/async-each-series/index.js:20:3)
    at Generate.generate (/home/user/.local/share/pnpm/global/5/.pnpm/base-generators@0.4.6/node_modules/base-generators/index.js:492:15)
    at /home/user/.local/share/pnpm/global/5/.pnpm/base-generators@0.4.6/node_modules/base-generators/index.js:475:18
    at iterate (/home/user/.local/share/pnpm/global/5/.pnpm/async-each-series@1.1.0/node_modules/async-each-series/index.js:8:5)
    at module.exports (/home/user/.local/share/pnpm/global/5/.pnpm/async-each-series@1.1.0/node_modules/async-each-series/index.js:20:3)
    at Generate.generate (/home/user/.local/share/pnpm/global/5/.pnpm/base-generators@0.4.6/node_modules/base-generators/index.js:474:24)
    at Generate.generate (/home/user/.local/share/pnpm/global/5/.pnpm/base-generators@0.4.6/node_modules/base-generators/index.js:463:23)
    at /home/user/.local/share/pnpm/global/5/.pnpm/generate@0.14.0/node_modules/generate/bin/generate.js:117:11
```

And as I found in similar issues you can directly use `generator.js` of the package that you want to use (`generate-license`), therefore the next command works as expected:

`gen ~/.local/share/pnpm/global/5/.pnpm/generate-license@1.0.0/node_modules/generate-license/generator.js`

Versions:

```text
pnpm 7.26.2
generate 0.14.0
generate-license 1.0.0
```

**Comment by jonschlinkert** [comment]
Thanks for letting us know. I'm working on a new version of Generate and this will help me ensure it works with popular package managers.

**Comment by Andrew15-5** [comment]
Great, I will be waiting for this version. Any pointers as to when this could happen? You can answer in years (like in 2 years), if the release date is still vague.

**Comment by jonschlinkert** [comment]
Lol, given my lack of open source contributions lately, I wouldn't blame anyone for thinking it would be years. I'm using the next version myself already (I think @doowb might be using it too), so hopefully much sooner than that. The main obstacle is finding the time to document changes, and maybe create a `compat` plugin to allow existing generators and plugins to be used with the new version. 

Thanks for your interest.

**Comment by Andrew15-5** [comment]
Ok, got it.

I almost always give "months/years" as an example. Because when I ask someone about a certain (due) date they always tell me they don't know. Then I "beg" them to tell any vague date/rough estimate and they still don't know. But when I start to ask "more than N month/years?" they suddenly say "Woah, no, not _that_ long". So basically, as a coder who want to know due dates, I have to "program" my request to get the answer.

But with FOSS project it's better to have low expectations because most of as just lazy. I have the same problem with my projects, but mainly I simply don't have enough time for them right now.
